name: Deploy to DigitalOcean

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["Static Analysis and Testing"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.outputs.type-check == 'success' && github.event.workflow_run.outputs.lint == 'success' && github.event.workflow_run.outputs.test == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.13.1"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: "144.126.249.162"
          username: "root"
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Create directory if it doesn't exist
            mkdir -p /var/www/addressdock

            # Kill existing process if running
            pkill -f "node dist/server.js" || true

            # Remove old dist directory
            rm -rf /var/www/addressdock/dist

            # Create a temporary directory for the new dist
            mkdir -p /tmp/addressdock-dist

      - name: Upload dist directory
        uses: appleboy/scp-action@master
        with:
          host: "144.126.249.162"
          username: "root"
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "dist/"
          target: "/tmp/addressdock-dist"
          strip_components: 0

      - name: Move dist to final location
        uses: appleboy/ssh-action@master
        with:
          host: "144.126.249.162"
          username: "root"
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Move the new dist directory to the final location
            mv /tmp/addressdock-dist/dist /var/www/addressdock/

            # Clean up temporary directory
            rm -rf /tmp/addressdock-dist

            # Start the application
            cd /var/www/addressdock
            nohup node dist/server.js > addressdock.log 2>&1 &
